Allow OnErrorCallbacks to return Promise<boolean>
bugsnag/bugsnag-js pull request #1224
Opened 2021-01-06 15:02 UTC by imjoehaines

## Goal

Currently an async `OnErrorCallback` can only return `Promise<void>` in the Typescript, which means they can't be used to prevent events from sending without causing a compile error. Returning/resolving a boolean value does work, so we can safely allow `Promise<boolean>` as a return type

2021-01-06 16:21 UTC, bengourley requested changes
Changes look good, but since we're in this area I checked the node-style callback for correctness too and found it was also incorrect.

It's hard to get the typing strict enough that it doesn't let people write invalid sync/async without preventing people from writing valid node-style callbacks. I had a quick go and got close, but the `never` in this example makes it unusable for non-trivial node-style callbacks…

![image](https://user-images.githubusercontent.com/609579/103792142-3193e280-503b-11eb-853d-6ed81243f1e3.png)

2021-01-07 09:51 UTC, imjoehaines commented
From some more testing, it looks like we can't make it perfectly strict because of how `void` works; I've pushed a fix for node style callbacks and split out each type so it's easier to see the three valid signatures — because of `void` you can still do 'invalid' things like returning an array, but we ignore anything that's not `false` so this shouldn't actually be a problem

2021-01-11 10:11 UTC, bengourley reviewed
![image](https://user-images.githubusercontent.com/609579/104168031-44b90080-53f5-11eb-95db-29a1601975c0.png)

Node-style callback signature is still not good. Is this the best we can do given the limitations?

2021-01-12 10:33 UTC, imjoehaines commented
> Node-style callback signature is still not good. Is this the best we can do given the limitations?

The alternatives are to either make it a union type, which makes `event` `any`:

```ts
type OnErrorCallback
  = ((event: Event) => void | boolean)
  | ((event: Event) => Promise<void | boolean>)
  | ((event: Event, cb: (err: null | Error, shouldSend?: boolean) => void) => void)

notify(event => event.stuff) // error TS7006: Parameter 'event' implicitly has an 'any' type.
```

or mark `cb` as always present, which isn't true but does seem to fix the other problems:

```ts
type OnErrorCallback = (event: Event, cb: (err: null | Error, shouldSend?: boolean) => void) => void | boolean | Promise<void | boolean>

notify(event => event.stuff) // works
notify((event, cb) => { cb(null) }) // works

notify(() => 1) // error TS2322: Type 'number' is not assignable to type 'boolean | void | Promise<boolean | void>'.
```

2021-01-13 09:29 UTC, bengourley commented
> mark cb as always present, which isn't true but does seem to fix the other problems:

I'd go with this. Marking it as always present doesn't mean people have to define it.

2021-01-13 10:15 UTC, bengourley approved these changes

2021-01-13 11:14 UTC, merged