[PLAT-10144] Update React Native CLI to install BugSnag CLI
bugsnag/bugsnag-js pull request #1990
Opened 2023-07-12 09:38 UTC by joshedney

## Goal

Update the React Native CLI  to install BugSnag CLI instead of the Source Maps package for the Android Integration. 

The RN 0.67 apk (Hermes) CLI build/test have been disabled due to issues with Hermes replacing the mapping file with its own Hermes binary file. This should be covered via the BAGP tests.

## Changeset

Update the `AutomateSymbolicationCommand.ts` to install the BugSnag CLI package for the Android integration.

## Testing

Covered by CI

2023-07-12 09:51 UTC, tomlongridge requested changes

2023-07-12 09:51 UTC, tomlongridge commented on packages/react-native-cli/package.json
> +  "version": "8.0.0",
Needs to be reverted

2023-07-12 09:51 UTC, tomlongridge commented on packages/react-native-cli/src/lib/Gradle.ts
> +const ENABLE_REACT_NATIVE_MAPPINGS = 'bugsnag {\n  uploadReactNativeMappings = false\n}\n'
I thought we weren't doing this any more? We should be warning if we find it enabled, but leaving it do default to `false` otherwise.

2023-07-12 09:51 UTC, tomlongridge commented on packages/react-native-cli/src/commands/AutomateSymbolicationCommand.ts
>  async function installJavaScriptPackage (projectRoot: string): Promise<void> {
We agreed that we would insert the command into the package.json as part of this init operation, under a prompt (e.g. "Do you want to add an NPM task to your package.json to upload Android source maps?")

2023-07-21 13:49 UTC, tomlongridge commented on packages/react-native-cli/src/lib/Gradle.ts
> +    if (/^\s*uploadReactNativeMappings\s*=\s*true/m.test(fileContents)) {
Remove references to uploadMappings, etc, in function/param names.
Remove the ENOENT catch and pattern not found checks

1. Read Gradle file
2. Check for uploadReactNativeMappings and warn if found
3. If uploadEndpoint or buildEndpoint are defined, insert `bugsnag {}` section

2023-07-21 13:49 UTC, tomlongridge commented on packages/react-native-cli/src/lib/__test__/Gradle.test.ts
> +//   expect(logger.warn).toHaveBeenCalledWith(`The uploadReactNativeMappings option for the Bugsnag Gradle plugin is currently enabled in /random/path/android/app/build.gradle.
Reinstate/update commented out sections

2023-08-07 14:54 UTC, tomlongridge commented on packages/react-native-cli/src/commands/AutomateSymbolicationCommand.ts
> +      }
```suggestion
      if (uploadUrl) {
        uploadCommand += ' --upload-api-root-url=' + uploadUrl
      }

      if (buildCommand) {
        buildCommand += ' --build-api-root-url=' + buildUrl
      }
```

2023-08-08 10:58 UTC, joshedney commented on packages/react-native-cli/src/lib/Gradle.ts
> +export async function addUploadEndpoint (projectRoot: string, uploadEndpoint: string | undefined, logger: Logger): Promise<void> {
There is not, looks like my IDE added it. I've removed it and re run the tests and it looks OK.

2023-08-16 16:01 UTC, lemnik commented on packages/react-native-cli/src/lib/Gradle.ts
> +  let match = fileContents.match(pattern)
with the above array suggestion:

```suggestion
  let match = patterns.find(search => fileContents.match(search))
```

2023-09-08 08:30 UTC, tomlongridge approved these changes
LGTM

2023-09-08 11:34 UTC, merged